name: Build U2IF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flavor_matrix: ${{ steps.flavorStep.outputs.flavors }}
      pico_sdk_cache_key: ${{ steps.pico-sdk-cache-key.outputs.cachekey }}
    steps:
      - uses: actions/checkout@v4      
      - id: flavorStep
        run: |
          FLAVORS=$(python3 ./firmware/build.py -flavors)
          echo "flavors=$FLAVORS" >> $GITHUB_OUTPUT
      - name: Install gcc-arm
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'
      - id: pico-sdk-cache-key
        run: |
          CACHEKEY=$(git submodule status firmware/pico-sdk)
          echo "cachekey=$CACHEKEY" >> $GITHUB_OUTPUT
      - name: Cache pico-sdk
        id: cache-pico-sdk
        uses: actions/cache@v4
        with:
          path: firmware/pico-sdk
          key: firmware-pico-sdk-${{ steps.pico-sdk-cache-key.outputs.cachekey }}
      - name: Get pico-sdk submodule
        if: steps.cache-pico-sdk.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive
          
  build_uf2:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.flavor_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc-arm
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'

      - name: Cache pico-sdk
        id: cache-pico-sdk
        uses: actions/cache@v4
        with:
          path: firmware/pico-sdk
          key: firmware-pico-sdk-${{ needs.setup.outputs.pico_sdk_cache_key }}

      - name: Build firmwares
        run: |
          arm-none-eabi-gcc --version
          cd firmware
          python3 build.py ${{ matrix.target }}
      - name: Add Build Artifacts to CI Run
        uses: actions/upload-artifact@v4
        with:
          name: u2if_${{ matrix.target }}.uf2
          path: firmware/release/u2if_${{ matrix.target }}.uf2
      - name: Add Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firmware/release/u2if_${{ matrix.target }}.uf2

  build_picotool:
    runs-on: ubuntu-latest
    needs: setup    
    steps:
      - uses: actions/checkout@v4
      - name: Cache pico-sdk
        id: cache-pico-sdk
        uses: actions/cache@v4
        with:
          path: firmware/pico-sdk
          key: firmware-pico-sdk-${{ needs.setup.outputs.pico_sdk_cache_key }}
      - name: install deps
        run: sudo apt-get install -y libusb-1.0 libusb-1.0.0-dev
      - name: clone picotool
        run: git clone https://github.com/raspberrypi/picotool.git
      - name: build picotool
        run: cd picotool && mkdir build && cd build && env PICO_SDK_PATH=../../firmware/pico-sdk cmake .. && make
      - name: Add Build Artifacts to CI Run
        uses: actions/upload-artifact@v4
        with:
          name: picotool
          path: firmware/picotool/build/picotool

  build_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: build python dist
        run: pip install --upgrade build && python -m build

      - name: Add Build Artifacts to CI Run
        uses: actions/upload-artifact@v4
        with:
          name: u2if_py
          path: dist/*
      - name: Add Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          
  build_docker:
    runs-on: ubuntu-latest
    needs:
      - build_py
      - build_uf2

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

