name: Build Python

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: build python dist
        run: pip install --upgrade build && python -m build

      - name: Add Build Artifacts to CI Run
        uses: actions/upload-artifact@v4
        with:
          name: u2if_py
          path: dist/*
      - name: Add Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
